DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE pc (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ipv4 TEXT NOT NULL
);

CREATE TABLE ping (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    pc_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    success BOOLEAN NOT NULL,
    sent INTEGER NOT NULL,
    lost INTEGER NOT NULL,
    max_ms FLOAT NOT NULL,
    min_ms FLOAT NOT NULL,
    avg_ms FLOAT NOT NULL,
    FOREIGN KEY (pc_id) REFERENCES pc (id)
);